- name: Run tests and generate coverage
  id: generate-test-coverage
  run: |
    source .venv/bin/activate
    pip install coverage pytest
    coverage run -m pytest mo4doutput/unittest/mstest/
    coverage xml -o coverage.xml
    cat coverage.xml

- name: Fetch coverage-upload script
  env:
    API_BASE: https://api.codeant.ai
  run: |
    curl -sS -X GET "${API_BASE}/pr/analysis/coverage/script/get" \
      --output upload_coverage.sh.b64

- name: Make script executable
  run: |
    base64 -d upload_coverage.sh.b64 > upload_coverage.sh
    chmod +x upload_coverage.sh

- name: Upload coverage and set status  
  env:
    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    REPO_NAME:    ${{ github.repository }}
    COMMIT_ID:    ${{ github.sha }}
  run: |
    bash upload_coverage.sh \
      -t "$ACCESS_TOKEN" \
      -r "$REPO_NAME" \
      -c "$COMMIT_ID" \
      -f coverage.xml \
      -p github \
      -b "${{ github.ref_name }}"
